Fix GCC 10 build error due to multiple definitions of do_perpacket_debug
[   97s] /usr/bin/ld: vrrp/libvrrp.a(vrrp_scheduler.o):./keepalived/vrrp/vrrp_scheduler.c:92: multiple definition of `do_perpacket_debug'; vrrp/libvrrp.a(vrrp.o):./keepalived/vrrp/vrrp.c:102: first defined here

In GCC 10 -fno-common is now the default:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678#c15

VRVDR-56009